### ISSUE TITLE
Issue Tracker

### ISSUE THREAD

**Issue by Wakandas-1st-Heero** [Wakandas-1st-Heero/Path2partnership#2]
Task List
1.  [ ] Figure out how to add and remove users from Godot map 
2.  [ ] Then figure out how to add images to users in the map
3.  [ ] Move the users with the point system
